ogeneral {
    hide_cursor = true
}

background {
    monitor =
    path = /home/henry/.local/share/wallpapers/norshore.png
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(d4783cff)
    inner_color = rgba(1c1c1cee)
    font_color = rgba(d5cfc6ff)
    placeholder_text = <i>Password...</i>
    fade_on_empty = false
    halign = center
    valign = center
}
